version: "3.1"
services:
    webserver:
      image: nginx:alpine
      container_name: political-ai-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      links:
        - php-fpm
#    microservice:
#      image: 'imihai/topic-modelling-ml:latest'
#      container_name: microservice
#      ports:
#      - "5777:5777"

    php-fpm:
      build:
        context: .
        dockerfile: ./Dockerfile
      #image: imihai/politic-ai:latest
      container_name: political-ai-php-fpm
      working_dir: /application
      ports:
       - "9000:9000"
       - "9001:9001"
      volumes:
        - ./application:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        #- ./phpdocker/php-fpm/ext-xdebug.ini:/etc/php/7.2/conf.d/ext-xdebug.ini
      environment:
        - DATABASE_IP
        - DATABASE_PORT
        - DATABASE_USERNAME
        - DATABASE_PASSWORD
        - DATABASE_NAME
        - MICROSERVICE_URL=http://microservice:5777

